/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimpleSQLScopeProvider extends DelegatingScopeProvider {
}
