/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.parser.antlr;

import com.google.inject.Inject;
import kcl.mdd.cw.sql.parser.antlr.internal.InternalSimpleSQLParser;
import kcl.mdd.cw.sql.services.SimpleSQLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SimpleSQLParser extends AbstractAntlrParser {

	@Inject
	private SimpleSQLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleSQLParser createParser(XtextTokenStream stream) {
		return new InternalSimpleSQLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SimpleSQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleSQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
