/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimpleSQLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("kcl/mdd/cw/sql/parser/antlr/internal/InternalSimpleSQL.tokens");
	}
}
