/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleSQLRuntimeModule extends AbstractSimpleSQLRuntimeModule {
}
