/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimpleSQLStandaloneSetup extends SimpleSQLStandaloneSetupGenerated {

	public static void doSetup() {
		new SimpleSQLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
