/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kcl.mdd.cw.sql.SimpleSQLRuntimeModule;
import kcl.mdd.cw.sql.SimpleSQLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SimpleSQLIdeSetup extends SimpleSQLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SimpleSQLRuntimeModule(), new SimpleSQLIdeModule()));
	}
	
}
