/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SimpleSQLUiModule extends AbstractSimpleSQLUiModule {

	public SimpleSQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
