/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.ui.tests;

import com.google.inject.Injector;
import kcl.mdd.cw.sql.ui.internal.SqlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SimpleSQLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SqlActivator.getInstance().getInjector("kcl.mdd.cw.sql.SimpleSQL");
	}

}
