/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSimpleSQLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage.eINSTANCE);
		return result;
	}
}
