/*
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.ui;

import com.google.inject.Injector;
import kcl.mdd.cw.sql.ui.internal.SqlActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpleSQLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SqlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SqlActivator activator = SqlActivator.getInstance();
		return activator != null ? activator.getInjector(SqlActivator.KCL_MDD_CW_SQL_SIMPLESQL) : null;
	}

}
