/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COLUMN DEF</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getName <em>Name</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getCOLUMN_DEF()
 * @model
 * @generated
 */
public interface COLUMN_DEF extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getCOLUMN_DEF_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link kcl.mdd.cw.sql.simpleSQL.TYPE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see kcl.mdd.cw.sql.simpleSQL.TYPE
   * @see #setType(TYPE)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getCOLUMN_DEF_Type()
   * @model
   * @generated
   */
  TYPE getType();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see kcl.mdd.cw.sql.simpleSQL.TYPE
   * @see #getType()
   * @generated
   */
  void setType(TYPE value);

} // COLUMN_DEF
