/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CREATE TABLE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getName <em>Name</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getDbName <em>Db Name</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getCREATE_TABLE()
 * @model
 * @generated
 */
public interface CREATE_TABLE extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getCREATE_TABLE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Db Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db Name</em>' attribute.
   * @see #setDbName(String)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getCREATE_TABLE_DbName()
   * @model
   * @generated
   */
  String getDbName();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getDbName <em>Db Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db Name</em>' attribute.
   * @see #getDbName()
   * @generated
   */
  void setDbName(String value);

  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getCREATE_TABLE_Columns()
   * @model containment="true"
   * @generated
   */
  EList<COLUMN_DEF> getColumns();

} // CREATE_TABLE
