/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>INNERJOIN</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.INNERJOIN#getTable <em>Table</em>}</li>
 * </ul>
 *
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getINNERJOIN()
 * @model
 * @generated
 */
public interface INNERJOIN extends Statement
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference.
   * @see #setTable(CREATE_TABLE)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getINNERJOIN_Table()
   * @model
   * @generated
   */
  CREATE_TABLE getTable();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.INNERJOIN#getTable <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' reference.
   * @see #getTable()
   * @generated
   */
  void setTable(CREATE_TABLE value);

} // INNERJOIN
