/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ORDERBY</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.ORDERBY#getTable <em>Table</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.ORDERBY#getCol <em>Col</em>}</li>
 * </ul>
 *
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getORDERBY()
 * @model
 * @generated
 */
public interface ORDERBY extends Statement
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference.
   * @see #setTable(CREATE_TABLE)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getORDERBY_Table()
   * @model
   * @generated
   */
  CREATE_TABLE getTable();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.ORDERBY#getTable <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' reference.
   * @see #getTable()
   * @generated
   */
  void setTable(CREATE_TABLE value);

  /**
   * Returns the value of the '<em><b>Col</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' reference.
   * @see #setCol(COLUMN_DEF)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getORDERBY_Col()
   * @model
   * @generated
   */
  COLUMN_DEF getCol();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.ORDERBY#getCol <em>Col</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col</em>' reference.
   * @see #getCol()
   * @generated
   */
  void setCol(COLUMN_DEF value);

} // ORDERBY
