/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage
 * @generated
 */
public interface SimpleSQLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpleSQLFactory eINSTANCE = kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>SELECT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SELECT</em>'.
   * @generated
   */
  SELECT createSELECT();

  /**
   * Returns a new object of class '<em>UPDATE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UPDATE</em>'.
   * @generated
   */
  UPDATE createUPDATE();

  /**
   * Returns a new object of class '<em>DELETE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DELETE</em>'.
   * @generated
   */
  DELETE createDELETE();

  /**
   * Returns a new object of class '<em>CREATE DB</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CREATE DB</em>'.
   * @generated
   */
  CREATE_DB createCREATE_DB();

  /**
   * Returns a new object of class '<em>CREATE TABLE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CREATE TABLE</em>'.
   * @generated
   */
  CREATE_TABLE createCREATE_TABLE();

  /**
   * Returns a new object of class '<em>COLUMN DEF</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COLUMN DEF</em>'.
   * @generated
   */
  COLUMN_DEF createCOLUMN_DEF();

  /**
   * Returns a new object of class '<em>INSERT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>INSERT</em>'.
   * @generated
   */
  INSERT createINSERT();

  /**
   * Returns a new object of class '<em>Insert List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert List</em>'.
   * @generated
   */
  Insert_List createInsert_List();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SimpleSQLPackage getSimpleSQLPackage();

} //SimpleSQLFactory
