/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLFactory
 * @model kind="package"
 * @generated
 */
public interface SimpleSQLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simpleSQL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mdd.kcl/cw/sql/SimpleSQL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simpleSQL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpleSQLPackage eINSTANCE = kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl.init();

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.ModelImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.StatementImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.ORDERBYImpl <em>ORDERBY</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.ORDERBYImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getORDERBY()
   * @generated
   */
  int ORDERBY = 2;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDERBY__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Col</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDERBY__COL = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>ORDERBY</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDERBY_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.WHEREImpl <em>WHERE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.WHEREImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getWHERE()
   * @generated
   */
  int WHERE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Db</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__DB = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__COLUMNS = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>WHERE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.INNERJOINImpl <em>INNERJOIN</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.INNERJOINImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getINNERJOIN()
   * @generated
   */
  int INNERJOIN = 4;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNERJOIN__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>INNERJOIN</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNERJOIN_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.SELECTImpl <em>SELECT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SELECTImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getSELECT()
   * @generated
   */
  int SELECT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Table</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__TABLE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>SELECT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.UPDATEImpl <em>UPDATE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.UPDATEImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getUPDATE()
   * @generated
   */
  int UPDATE = 6;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cols</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE__COLS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE__DATA = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>UPDATE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.DELETEImpl <em>DELETE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.DELETEImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getDELETE()
   * @generated
   */
  int DELETE = 7;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE__DATA = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>DELETE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.CREATE_DBImpl <em>CREATE DB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.CREATE_DBImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getCREATE_DB()
   * @generated
   */
  int CREATE_DB = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_DB__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>CREATE DB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_DB_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.CREATE_TABLEImpl <em>CREATE TABLE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.CREATE_TABLEImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getCREATE_TABLE()
   * @generated
   */
  int CREATE_TABLE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Db</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE__DB = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE__COLUMNS = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>CREATE TABLE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.COLUMN_DEFImpl <em>COLUMN DEF</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.COLUMN_DEFImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getCOLUMN_DEF()
   * @generated
   */
  int COLUMN_DEF = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_DEF__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_DEF__TYPE = 1;

  /**
   * The number of structural features of the '<em>COLUMN DEF</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.INSERTImpl <em>INSERT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.INSERTImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getINSERT()
   * @generated
   */
  int INSERT = 11;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__DATA = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>INSERT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.Insert_ListImpl <em>Insert List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.impl.Insert_ListImpl
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getInsert_List()
   * @generated
   */
  int INSERT_LIST = 12;

  /**
   * The feature id for the '<em><b>Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_LIST__DATA = 0;

  /**
   * The number of structural features of the '<em>Insert List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link kcl.mdd.cw.sql.simpleSQL.TYPE <em>TYPE</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.mdd.cw.sql.simpleSQL.TYPE
   * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getTYPE()
   * @generated
   */
  int TYPE = 13;


  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.mdd.cw.sql.simpleSQL.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.ORDERBY <em>ORDERBY</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ORDERBY</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.ORDERBY
   * @generated
   */
  EClass getORDERBY();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.ORDERBY#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.ORDERBY#getTable()
   * @see #getORDERBY()
   * @generated
   */
  EReference getORDERBY_Table();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.ORDERBY#getCol <em>Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Col</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.ORDERBY#getCol()
   * @see #getORDERBY()
   * @generated
   */
  EReference getORDERBY_Col();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.WHERE <em>WHERE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>WHERE</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.WHERE
   * @generated
   */
  EClass getWHERE();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.WHERE#getName()
   * @see #getWHERE()
   * @generated
   */
  EAttribute getWHERE_Name();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getDb <em>Db</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Db</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.WHERE#getDb()
   * @see #getWHERE()
   * @generated
   */
  EReference getWHERE_Db();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.WHERE#getColumns()
   * @see #getWHERE()
   * @generated
   */
  EReference getWHERE_Columns();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.INNERJOIN <em>INNERJOIN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INNERJOIN</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.INNERJOIN
   * @generated
   */
  EClass getINNERJOIN();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.INNERJOIN#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.INNERJOIN#getTable()
   * @see #getINNERJOIN()
   * @generated
   */
  EReference getINNERJOIN_Table();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.SELECT <em>SELECT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SELECT</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.SELECT
   * @generated
   */
  EClass getSELECT();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.SELECT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.SELECT#getName()
   * @see #getSELECT()
   * @generated
   */
  EAttribute getSELECT_Name();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.SELECT#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Table</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.SELECT#getTable()
   * @see #getSELECT()
   * @generated
   */
  EAttribute getSELECT_Table();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.UPDATE <em>UPDATE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>UPDATE</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.UPDATE
   * @generated
   */
  EClass getUPDATE();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.UPDATE#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.UPDATE#getTable()
   * @see #getUPDATE()
   * @generated
   */
  EReference getUPDATE_Table();

  /**
   * Returns the meta object for the reference list '{@link kcl.mdd.cw.sql.simpleSQL.UPDATE#getCols <em>Cols</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Cols</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.UPDATE#getCols()
   * @see #getUPDATE()
   * @generated
   */
  EReference getUPDATE_Cols();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.mdd.cw.sql.simpleSQL.UPDATE#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.UPDATE#getData()
   * @see #getUPDATE()
   * @generated
   */
  EReference getUPDATE_Data();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.DELETE <em>DELETE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DELETE</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.DELETE
   * @generated
   */
  EClass getDELETE();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.DELETE#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.DELETE#getTable()
   * @see #getDELETE()
   * @generated
   */
  EReference getDELETE_Table();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.mdd.cw.sql.simpleSQL.DELETE#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.DELETE#getData()
   * @see #getDELETE()
   * @generated
   */
  EReference getDELETE_Data();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_DB <em>CREATE DB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CREATE DB</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.CREATE_DB
   * @generated
   */
  EClass getCREATE_DB();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_DB#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.CREATE_DB#getName()
   * @see #getCREATE_DB()
   * @generated
   */
  EAttribute getCREATE_DB_Name();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE <em>CREATE TABLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CREATE TABLE</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE
   * @generated
   */
  EClass getCREATE_TABLE();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getName()
   * @see #getCREATE_TABLE()
   * @generated
   */
  EAttribute getCREATE_TABLE_Name();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getDb <em>Db</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Db</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getDb()
   * @see #getCREATE_TABLE()
   * @generated
   */
  EReference getCREATE_TABLE_Db();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.CREATE_TABLE#getColumns()
   * @see #getCREATE_TABLE()
   * @generated
   */
  EReference getCREATE_TABLE_Columns();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF <em>COLUMN DEF</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>COLUMN DEF</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF
   * @generated
   */
  EClass getCOLUMN_DEF();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getName()
   * @see #getCOLUMN_DEF()
   * @generated
   */
  EAttribute getCOLUMN_DEF_Name();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF#getType()
   * @see #getCOLUMN_DEF()
   * @generated
   */
  EAttribute getCOLUMN_DEF_Type();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.INSERT <em>INSERT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INSERT</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.INSERT
   * @generated
   */
  EClass getINSERT();

  /**
   * Returns the meta object for the reference '{@link kcl.mdd.cw.sql.simpleSQL.INSERT#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.INSERT#getTable()
   * @see #getINSERT()
   * @generated
   */
  EReference getINSERT_Table();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.mdd.cw.sql.simpleSQL.INSERT#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.INSERT#getData()
   * @see #getINSERT()
   * @generated
   */
  EReference getINSERT_Data();

  /**
   * Returns the meta object for class '{@link kcl.mdd.cw.sql.simpleSQL.Insert_List <em>Insert List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert List</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.Insert_List
   * @generated
   */
  EClass getInsert_List();

  /**
   * Returns the meta object for the attribute '{@link kcl.mdd.cw.sql.simpleSQL.Insert_List#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.Insert_List#getData()
   * @see #getInsert_List()
   * @generated
   */
  EAttribute getInsert_List_Data();

  /**
   * Returns the meta object for enum '{@link kcl.mdd.cw.sql.simpleSQL.TYPE <em>TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>TYPE</em>'.
   * @see kcl.mdd.cw.sql.simpleSQL.TYPE
   * @generated
   */
  EEnum getTYPE();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimpleSQLFactory getSimpleSQLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.ModelImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.StatementImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.ORDERBYImpl <em>ORDERBY</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.ORDERBYImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getORDERBY()
     * @generated
     */
    EClass ORDERBY = eINSTANCE.getORDERBY();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDERBY__TABLE = eINSTANCE.getORDERBY_Table();

    /**
     * The meta object literal for the '<em><b>Col</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDERBY__COL = eINSTANCE.getORDERBY_Col();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.WHEREImpl <em>WHERE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.WHEREImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getWHERE()
     * @generated
     */
    EClass WHERE = eINSTANCE.getWHERE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE__NAME = eINSTANCE.getWHERE_Name();

    /**
     * The meta object literal for the '<em><b>Db</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE__DB = eINSTANCE.getWHERE_Db();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE__COLUMNS = eINSTANCE.getWHERE_Columns();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.INNERJOINImpl <em>INNERJOIN</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.INNERJOINImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getINNERJOIN()
     * @generated
     */
    EClass INNERJOIN = eINSTANCE.getINNERJOIN();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INNERJOIN__TABLE = eINSTANCE.getINNERJOIN_Table();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.SELECTImpl <em>SELECT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SELECTImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getSELECT()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSELECT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__NAME = eINSTANCE.getSELECT_Name();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__TABLE = eINSTANCE.getSELECT_Table();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.UPDATEImpl <em>UPDATE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.UPDATEImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getUPDATE()
     * @generated
     */
    EClass UPDATE = eINSTANCE.getUPDATE();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE__TABLE = eINSTANCE.getUPDATE_Table();

    /**
     * The meta object literal for the '<em><b>Cols</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE__COLS = eINSTANCE.getUPDATE_Cols();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE__DATA = eINSTANCE.getUPDATE_Data();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.DELETEImpl <em>DELETE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.DELETEImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getDELETE()
     * @generated
     */
    EClass DELETE = eINSTANCE.getDELETE();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE__TABLE = eINSTANCE.getDELETE_Table();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE__DATA = eINSTANCE.getDELETE_Data();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.CREATE_DBImpl <em>CREATE DB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.CREATE_DBImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getCREATE_DB()
     * @generated
     */
    EClass CREATE_DB = eINSTANCE.getCREATE_DB();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE_DB__NAME = eINSTANCE.getCREATE_DB_Name();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.CREATE_TABLEImpl <em>CREATE TABLE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.CREATE_TABLEImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getCREATE_TABLE()
     * @generated
     */
    EClass CREATE_TABLE = eINSTANCE.getCREATE_TABLE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE_TABLE__NAME = eINSTANCE.getCREATE_TABLE_Name();

    /**
     * The meta object literal for the '<em><b>Db</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_TABLE__DB = eINSTANCE.getCREATE_TABLE_Db();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_TABLE__COLUMNS = eINSTANCE.getCREATE_TABLE_Columns();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.COLUMN_DEFImpl <em>COLUMN DEF</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.COLUMN_DEFImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getCOLUMN_DEF()
     * @generated
     */
    EClass COLUMN_DEF = eINSTANCE.getCOLUMN_DEF();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_DEF__NAME = eINSTANCE.getCOLUMN_DEF_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_DEF__TYPE = eINSTANCE.getCOLUMN_DEF_Type();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.INSERTImpl <em>INSERT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.INSERTImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getINSERT()
     * @generated
     */
    EClass INSERT = eINSTANCE.getINSERT();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__TABLE = eINSTANCE.getINSERT_Table();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__DATA = eINSTANCE.getINSERT_Data();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.impl.Insert_ListImpl <em>Insert List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.impl.Insert_ListImpl
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getInsert_List()
     * @generated
     */
    EClass INSERT_LIST = eINSTANCE.getInsert_List();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_LIST__DATA = eINSTANCE.getInsert_List_Data();

    /**
     * The meta object literal for the '{@link kcl.mdd.cw.sql.simpleSQL.TYPE <em>TYPE</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.mdd.cw.sql.simpleSQL.TYPE
     * @see kcl.mdd.cw.sql.simpleSQL.impl.SimpleSQLPackageImpl#getTYPE()
     * @generated
     */
    EEnum TYPE = eINSTANCE.getTYPE();

  }

} //SimpleSQLPackage
