/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
