/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UPDATE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.UPDATE#getTable <em>Table</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.UPDATE#getCols <em>Cols</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.UPDATE#getData <em>Data</em>}</li>
 * </ul>
 *
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getUPDATE()
 * @model
 * @generated
 */
public interface UPDATE extends Statement
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference.
   * @see #setTable(CREATE_TABLE)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getUPDATE_Table()
   * @model
   * @generated
   */
  CREATE_TABLE getTable();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.UPDATE#getTable <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' reference.
   * @see #getTable()
   * @generated
   */
  void setTable(CREATE_TABLE value);

  /**
   * Returns the value of the '<em><b>Cols</b></em>' reference list.
   * The list contents are of type {@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cols</em>' reference list.
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getUPDATE_Cols()
   * @model
   * @generated
   */
  EList<COLUMN_DEF> getCols();

  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference list.
   * The list contents are of type {@link kcl.mdd.cw.sql.simpleSQL.Insert_List}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference list.
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getUPDATE_Data()
   * @model containment="true"
   * @generated
   */
  EList<Insert_List> getData();

} // UPDATE
