/**
 * generated by Xtext 2.20.0
 */
package kcl.mdd.cw.sql.simpleSQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WHERE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getName <em>Name</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getDb <em>Db</em>}</li>
 *   <li>{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getWHERE()
 * @model
 * @generated
 */
public interface WHERE extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getWHERE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Db</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db</em>' reference.
   * @see #setDb(CREATE_DB)
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getWHERE_Db()
   * @model
   * @generated
   */
  CREATE_DB getDb();

  /**
   * Sets the value of the '{@link kcl.mdd.cw.sql.simpleSQL.WHERE#getDb <em>Db</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db</em>' reference.
   * @see #getDb()
   * @generated
   */
  void setDb(CREATE_DB value);

  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link kcl.mdd.cw.sql.simpleSQL.COLUMN_DEF}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see kcl.mdd.cw.sql.simpleSQL.SimpleSQLPackage#getWHERE_Columns()
   * @model containment="true"
   * @generated
   */
  EList<COLUMN_DEF> getColumns();

} // WHERE
